<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ant.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/ant.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armature">
        <T is={gltf.nodes.body1} />
        <T is={gltf.nodes.leg_targetl} />
        <T is={gltf.nodes.leg_targetr} />
        <T is={gltf.nodes.leg_polel} />
        <T is={gltf.nodes.leg_poler} />
        <T.Group name="arms001" position={[0, 0.02, -0.01]} />
        <T.Group name="eyes" position={[0, 0.02, -0.01]} />
        <T.Group name="head001" position={[0, 0.02, -0.01]} />
        <T.Group name="mouth" position={[0, 0.02, -0.01]} />
        <T.Group name="torso" position={[0, 0.02, -0.01]} />
        <T.SkinnedMesh
          name="Cube010"
          geometry={gltf.nodes.Cube010.geometry}
          material={gltf.materials['arms.002']}
          skeleton={gltf.nodes.Cube010.skeleton}
        />
        <T.SkinnedMesh
          name="Cube011"
          geometry={gltf.nodes.Cube011.geometry}
          material={gltf.materials['head.002']}
          skeleton={gltf.nodes.Cube011.skeleton}
        />
        <T.SkinnedMesh
          name="Cube012"
          geometry={gltf.nodes.Cube012.geometry}
          material={gltf.materials['mouth.001']}
          skeleton={gltf.nodes.Cube012.skeleton}
        />
        <T.SkinnedMesh
          name="Cube013"
          geometry={gltf.nodes.Cube013.geometry}
          material={gltf.materials['Material.002']}
          skeleton={gltf.nodes.Cube013.skeleton}
        />
        <T.SkinnedMesh
          name="Sphere001"
          geometry={gltf.nodes.Sphere001.geometry}
          material={gltf.materials['eyes.001']}
          skeleton={gltf.nodes.Sphere001.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
